HMS/Models/Hostel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace HMS.Models
{
    public class Hostel
    {
        public int ID { get; set; }
        public string Name { get; set; }

        public string Address { get; set; }

        public double Contact { get; set; }
        

        public int Capacity { get; set; }

        public int Rooms { get; set; }

        public int Seaters { get; set; }

        public int EmptySeats { get; set; }

        public float Fees{ get; set; }

        [NotMapped]
        public IFormFile ProfileImage { get; set; }
        public string ProfileImagePath { get; set; }

        public virtual List<Student> Students{ get; set; }

    }
}

HMS/Controllers/HostelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HMS;
using HMS.Models;
using Microsoft.Extensions.Hosting;

namespace HMS.Controllers
{
    public class HostelsController : Controller
    {
        private readonly HMSDbcontext _context;

        public HostelsController(HMSDbcontext context)
         {
            _context = context;
        }

        // GET: Hostels
        public async Task<IActionResult> Index()
        {
              return View(await _context.Hostels.ToListAsync());
        }

        // GET: Hostels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Hostels == null)
            {
                return NotFound();
            }

            var hostel = await _context.Hostels
                .FirstOrDefaultAsync(m => m.ID == id);
            if (hostel == null)
            {
                return NotFound();
            }

            return View(hostel);
        }

        // GET: Hostels/Create
        public IActionResult Create()
        {
            
            
            return View();
        }

        // POST: Hostels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Hostel hostel)
        {
           //var profileImage = hostel.ProfileImage;
            
           // var fileName = profileImage.FileName;
           // var uniqueFileName =$"{Guid.NewGuid()}_{fileName}";
           // var relativePath = $"/Images/Profiles/{uniqueFileName}";
           // var currentAppPath = Directory.GetCurrentDirectory();
           //var fullFilePath = Path.Combine(currentAppPath,$"wwwroot/{relativePath}");

           // var stream = System.IO.File.Create(fullFilePath);
           // profileImage.CopyTo(stream);

            var relativePath = saveProfileImage(hostel.ProfileImage);
           // hostel.ProfileImagePath = relativePath;
            
            if (ModelState.IsValid)
            {
                hostel.ProfileImagePath = relativePath;
                _context.Hostels.Add(hostel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hostel);
        }

        // GET: Hostels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
           
            if (id == null || _context.Hostels == null)
            {
                return NotFound();
            }

            var hostel = await _context.Hostels.FindAsync(id);
            if (hostel == null)
            {
                return NotFound();
            }
            return View(hostel);
        }

        // POST: Hostels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Address,Contact,Capacity,Rooms,Seaters,EmptySeats,Fees")] Hostel hostel)
        {
            if (id != hostel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var relativePath = saveProfileImage(hostel.ProfileImage);
                try
                {
                    hostel.ProfileImagePath = relativePath;
                    _context.Update(hostel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HostelExists(hostel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(hostel);
        }

        // GET: Hostels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Hostels == null)
            {
                return NotFound();
            }

            var hostel = await _context.Hostels
                .FirstOrDefaultAsync(m => m.ID == id);
            if (hostel == null)
            {
                return NotFound();
            }

            return View(hostel);
        }

        // POST: Hostels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Hostels == null)
            {
                return Problem("Entity set 'HMSDbcontext.Hostels'  is null.");
            }
            var hostel = await _context.Hostels.FindAsync(id);
            if (hostel != null)
            {
                _context.Hostels.Remove(hostel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HostelExists(int id)
        {
          return _context.Hostels.Any(e => e.ID == id);
        }


        private string saveProfileImage(IFormFile profileImage)
        {
           

            var fileName = profileImage.FileName;
            var uniqueFileName = $"{Guid.NewGuid()}_{fileName}";
            var relativePath = $"/Images/Profiles/{uniqueFileName}";
            var currentAppPath = Directory.GetCurrentDirectory();
            var fullFilePath = Path.Combine(currentAppPath, $"wwwroot/{relativePath}");

            var stream = System.IO.File.Create(fullFilePath);
            profileImage.CopyTo(stream);
            return relativePath;
        }
    }
}

HMS/Views/Hostels/Create.cshtml
@model HMS.Models.Hostel

@{
    ViewData["Title"] = "Create";
}



<h4> Add Hostel</h4>
<hr />
<div class="row m-4">
    <div class="col-md-6">
        <form asp-controller="Hostels" asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" maxlength="10"/>
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rooms" class="control-label"></label>
                <input asp-for="Rooms" class="form-control" />
                <span asp-validation-for="Rooms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Seaters" class="control-label"></label>
                <input asp-for="Seaters" class="form-control" />
                <span asp-validation-for="Seaters" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmptySeats" class="control-label"></label>
                <input asp-for="EmptySeats" class="form-control" />
                <span asp-validation-for="EmptySeats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fees" class="control-label"></label>
                <input asp-for="Fees" class="form-control" />
                <span asp-validation-for="Fees" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ProfileImage" class="control-label"></label>
                <input asp-for="ProfileImage" class="form-control" />
               @*<span asp-validation-for="Fees" class="text-danger"></span>*@
            </div>
            <div class="form-group">
               
                <input type="submit" value="Create" class="btn btn-primary"  />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HMS/Views/Hostels/Delete.cshtml
@model HMS.Models.Hostel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hostel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rooms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rooms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Seaters)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Seaters)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmptySeats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmptySeats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fees)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fees)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HMS/Views/Hostels/Details.cshtml
@model HMS.Models.Hostel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Hostel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rooms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rooms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Seaters)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Seaters)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmptySeats)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmptySeats)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fees)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fees)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID"><i class="bi bi-clipboard-check-fill"></i></a> |
    <a asp-action="Index"><i class="bi bi-backspace-fill"></i></a>
</div>

HMS/Views/Hostels/Edit.cshtml
@model HMS.Models.Hostel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Hostel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="application/x-www-form-urlencoded">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rooms" class="control-label"></label>
                <input asp-for="Rooms" class="form-control" />
                <span asp-validation-for="Rooms" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Seaters" class="control-label"></label>
                <input asp-for="Seaters" class="form-control" />
                <span asp-validation-for="Seaters" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmptySeats" class="control-label"></label>
                <input asp-for="EmptySeats" class="form-control" />
                <span asp-validation-for="EmptySeats" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fees" class="control-label"></label>
                <input asp-for="Fees" class="form-control" />
                <span asp-validation-for="Fees" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfileImage" class="control-label"></label>
                <input asp-for="ProfileImage" class="form-control" />
                @*<span asp-validation-for="Fees" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HMS/Views/Hostels/Index.cshtml
@model IEnumerable<HMS.Models.Hostel>


@{
    ViewData["Title"] = "Index";
}

<h1>Hostels</h1>

@*p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProfileImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rooms)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seaters)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmptySeats)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fees)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            var profilesrc = string.IsNullOrEmpty(item.ProfileImagePath)
            ? "/Images/Profiles/download.png"
            : item.ProfileImagePath;
            <tr>
          
            <td>
                    <img src="@profilesrc" alt="Girl in a jacket" width="30">
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contact)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rooms)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Seaters)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmptySeats)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fees)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.ID"><i class="bi bi-pencil-square"></i></a> |
                    <a asp-action="Details" asp-route-id="@item.ID"><i class="bi bi-clipboard-check-fill"></i></a> |
                    <a asp-action="Delete" asp-route-id="@item.ID"><span id="boot-icon" class="bi bi-trash" style=" color: rgb(255, 0, 0);"></span></a>
            </td>
        </tr>
}
    </tbody>
</table>